server:
  port: 8084

spring:
  application:
    name: venta-service
  datasource:
    url: jdbc:mysql://localhost:3306/venta_service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      resource-server:
        jwt:
          secret-key: MiSuperClaveSegura1234567890!@#$

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true